"""
Inline the local modules into one file, which is what actually deploys.

GenVM loads a single source file with no access to siblings, so the
`from contracts.policy import ...` that works under pytest fails on chain.
Rather than give that up and lose a separately testable arithmetic core,
this pastes the modules together in dependency order.

Edit the modules. Never edit the bundle: it is regenerated, and a test
asserts it matches its sources so a stale one cannot be deployed.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "contracts"
OUT = CONTRACTS / "peril_bundle.py"

# Order matters: policy defines what peril imports.
PARTS = ["policy.py", "peril.py"]

_LOCAL_IMPORT = re.compile(
    r"^from contracts\.[a-z_]+ import \([^)]*\)\n|^from contracts\.[a-z_]+ import .*\n",
    re.MULTILINE,
)


def strip_docstring(text: str) -> str:
    """
    Drop a module's leading docstring.

    Only the first one survives in the bundle, otherwise the file has a
    string literal sitting between two blocks of code for every module
    pasted in, which reads as debris to anyone opening the deployed source.
    """
    stripped = text.lstrip()
    if not stripped.startswith('"""'):
        return text
    end = stripped.find('"""', 3)
    if end == -1:
        return text
    return stripped[end + 3 :].lstrip("\n")


def build() -> str:
    header = ""
    body = []

    for name in PARTS:
        text = (CONTRACTS / name).read_text(encoding="utf-8")

        # The Depends line has to be the very first line of the deployed
        # file, and only one of them may exist.
        lines = text.split("\n")
        if lines and lines[0].startswith("# {") and not header:
            header = lines[0]
        if lines and lines[0].startswith("# {"):
            text = "\n".join(lines[1:])

        text = _LOCAL_IMPORT.sub("", text)
        body.append(f"# ---- {name} " + "-" * (66 - len(name)) + "\n\n" + strip_docstring(text).rstrip())

    return (
        header
        + "\n"
        + '"""\nGenerated by deploy/build_bundle.py. Do not edit.\n\n'
        + "The deployable form of PERIL: contracts/policy.py and\n"
        + "contracts/peril.py pasted together, because GenVM loads one file\n"
        + "and cannot see sibling modules. Edit those, then rebuild.\n"
        + '"""\n\n'
        + "\n\n\n".join(body)
        + "\n"
    )


if __name__ == "__main__":
    out = build()
    OUT.write_text(out, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT} ({len(out)} bytes)")
