"""
Inline the local modules into one file, which is what actually deploys.

GenVM loads a single source file with no access to siblings, so the
`from contracts.policy import ...` that works under pytest fails on chain.
Rather than give that up and lose a separately testable arithmetic core,
this pastes the modules together in dependency order.

Edit the modules. Never edit the bundle: it is regenerated, and a test
asserts it matches its sources so a stale one cannot be deployed.
"""

import ast
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "contracts"
OUT = CONTRACTS / "peril_bundle.py"

# Order matters: policy defines what peril imports.
PARTS = ["policy.py", "peril.py"]

_LOCAL_IMPORT = re.compile(
    r"^from contracts\.[a-z_]+ import \([^)]*\)\n|^from contracts\.[a-z_]+ import .*\n",
    re.MULTILINE,
)


def strip_docstring(text: str) -> str:
    """
    Drop a module's leading docstring.

    Only the first one survives in the bundle, otherwise the file has a
    string literal sitting between two blocks of code for every module
    pasted in, which reads as debris to anyone opening the deployed source.
    """
    stripped = text.lstrip()
    if not stripped.startswith('"""'):
        return text
    end = stripped.find('"""', 3)
    if end == -1:
        return text
    return stripped[end + 3 :].lstrip("\n")


def strip_for_chain(source: str) -> str:
    """
    Drop comments and docstrings from the deployed form.

    A deploy costs gas per byte of source, and Bradbury refuses any
    transaction above 16,777,216 gas without an error: the node returns a
    hash and the transaction never exists. The commented bundle came to
    17.7M. The commented modules stay in the repo; only the copy sent to the
    chain loses them, and parsing it back proves nothing but that was lost.
    """
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef)):
            first = node.body[0] if node.body else None
            if (
                isinstance(first, ast.Expr)
                and isinstance(first.value, ast.Constant)
                and isinstance(first.value.value, str)
            ):
                node.body = node.body[1:] or [ast.Pass()]
    return ast.unparse(tree)


def build() -> str:
    header = ""
    body = []

    for name in PARTS:
        text = (CONTRACTS / name).read_text(encoding="utf-8")

        # The runner header (the "# v0.3.0" line, then Depends) has to open
        # the deployed file, and only one copy of it may exist.
        lines = text.split("\n")
        head = []
        while lines and (lines[0].startswith("# v") or lines[0].startswith("# {")):
            head.append(lines.pop(0))
        if head and not header:
            header = "\n".join(head)
        text = "\n".join(lines)

        text = _LOCAL_IMPORT.sub("", text)
        body.append(f"# ---- {name} " + "-" * (66 - len(name)) + "\n\n" + strip_docstring(text).rstrip())

    return (
        header
        + "\n"
        # Not a comment: GenVM reads the whole leading comment block as the
        # runner header, and any comment line under it fails the deploy
        # with "invalid_contract: trailing characters".
        + '"""Generated by deploy/build_bundle.py from contracts/policy.py and\n'
        + 'contracts/peril.py. Comments removed to fit the gas cap; read those."""\n'
        + strip_for_chain("\n\n\n".join(body))
        + "\n"
    )


if __name__ == "__main__":
    out = build()
    OUT.write_text(out, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT} ({len(out)} bytes)")
