# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }
"""Generated by deploy/build_bundle.py from contracts/policy.py and
contracts/peril.py. Comments removed to fit the gas cap; read those."""
_ISO_MIN = len('2026-09-07T14:25:18Z')

def _days_from_civil(y: int, m: int, d: int) -> int:
    y -= 1 if m <= 2 else 0
    era = (y if y >= 0 else y - 399) // 400
    yoe = y - era * 400
    doy = (153 * (m + (-3 if m > 2 else 9)) + 2) // 5 + d - 1
    doe = yoe * 365 + yoe // 4 - yoe // 100 + doy
    return era * 146097 + doe - 719468

def _int(text: str) -> int:
    if not text or not text.isdigit():
        raise ValueError('not a number: ' + repr(text))
    return int(text)

def parse_iso(stamp: str) -> int:
    s = (stamp or '').strip()
    if len(s) < _ISO_MIN or s[4] != '-' or s[7] != '-' or (s[10] != 'T'):
        raise ValueError('not an ISO-8601 UTC timestamp: ' + repr(stamp))
    if not s.endswith('Z'):
        raise ValueError('only UTC timestamps ending in Z are accepted: ' + repr(stamp))
    if s[13] != ':' or s[16] != ':':
        raise ValueError('malformed time component: ' + repr(stamp))
    year = _int(s[0:4])
    month = _int(s[5:7])
    day = _int(s[8:10])
    hour = _int(s[11:13])
    minute = _int(s[14:16])
    second = _int(s[17:19])
    if not 1 <= month <= 12 or not 1 <= day <= 31:
        raise ValueError('date out of range: ' + repr(stamp))
    if hour > 23 or minute > 59 or second > 60:
        raise ValueError('time out of range: ' + repr(stamp))
    return _days_from_civil(year, month, day) * 86400 + hour * 3600 + minute * 60 + second

def parse_date(day: str) -> int:
    s = (day or '').strip()
    if len(s) != 10 or s[4] != '-' or s[7] != '-':
        raise ValueError('not a YYYY-MM-DD date: ' + repr(day))
    return _days_from_civil(_int(s[0:4]), _int(s[5:7]), _int(s[8:10])) * 86400

def outage_minutes(created_at: str, resolved_at: str) -> int:
    start = parse_iso(created_at)
    end = parse_iso(resolved_at)
    if end < start:
        raise ValueError('incident resolved before it started')
    return (end - start) // 60
PAYS = 'pays'
UNDER_THRESHOLD = 'under_threshold'
OUTSIDE_WINDOW = 'outside_window'
UNRESOLVED = 'unresolved'

class Assessment:

    def __init__(self, outcome: str, minutes: int, reason: str):
        self.outcome = outcome
        self.minutes = minutes
        self.reason = reason

    @property
    def pays(self) -> bool:
        return self.outcome == PAYS

def assess(created_at: str, resolved_at: str, window_start: str, window_end: str, threshold_minutes: int) -> Assessment:
    if not (resolved_at or '').strip():
        return Assessment(UNRESOLVED, 0, 'the incident is still open, so it has no final duration to measure')
    minutes = outage_minutes(created_at, resolved_at)
    began = parse_iso(created_at)
    if began < parse_date(window_start) or began >= parse_date(window_end):
        return Assessment(OUTSIDE_WINDOW, minutes, 'the incident began outside the covered window')
    if minutes < threshold_minutes:
        return Assessment(UNDER_THRESHOLD, minutes, f'{minutes} minutes is under the {threshold_minutes} minute threshold')
    return Assessment(PAYS, minutes, f'{minutes} minutes meets the {threshold_minutes} minute threshold')
from dataclasses import dataclass
from genlayer import *
_PAYOUT_MULTIPLE = 10
_MIN_THRESHOLD = 15
_MAX_THRESHOLD = 1440
STATE_OPEN = 'open'
STATE_PAID = 'paid'
STATE_CLOSED = 'closed'

def _times_from_incident(body: str) -> dict:
    import json
    data = json.loads(body)
    incident = data.get('incident') or {}
    return {'id': str(incident.get('id') or ''), 'created_at': str(incident.get('created_at') or ''), 'resolved_at': str(incident.get('resolved_at') or '')}

@allow_storage
@dataclass
class Policy:
    host: str
    window_start: str
    window_end: str
    threshold_minutes: u256
    premium: u256
    payout: u256
    holder: Address
    state: str
    incident_id: str
    outcome: str
    minutes: u256
    reason: str

class Peril(gl.Contract):
    covers: TreeMap[str, str]
    policies: TreeMap[str, Policy]
    ids: DynArray[str]
    locked: u256
    pool: u256

    def __init__(self):
        self.covers['cloudflare'] = 'www.cloudflarestatus.com'
        self.covers['github'] = 'www.githubstatus.com'
        self.covers['openai'] = 'status.openai.com'
        self.covers['discord'] = 'discordstatus.com'
        self.covers['vercel'] = 'www.vercel-status.com'
        self.covers['netlify'] = 'www.netlifystatus.com'
        self.covers['npm'] = 'status.npmjs.org'
        self.locked = u256(0)
        self.pool = u256(0)

    @gl.public.write.payable
    def fund(self) -> dict:
        amount = gl.message.value
        if amount <= 0:
            raise gl.vm.UserError('send value with this call')
        self.pool = u256(self.pool + amount)
        return {'pool': str(self.pool), 'locked': str(self.locked)}

    @gl.public.write.payable
    def buy(self, policy_id: str, cover: str, window_start: str, window_end: str, threshold_minutes: int) -> dict:
        key = policy_id.strip().lower()
        if key in self.policies:
            raise gl.vm.UserError(f'policy already exists: {key}')
        name = cover.strip().lower()
        if name not in self.covers:
            raise gl.vm.UserError('not a covered service; call covered() for the list')
        threshold = int(threshold_minutes)
        if threshold < _MIN_THRESHOLD or threshold > _MAX_THRESHOLD:
            raise gl.vm.UserError(f'threshold must be between {_MIN_THRESHOLD} and {_MAX_THRESHOLD} minutes')
        start = parse_date(window_start)
        end = parse_date(window_end)
        if end <= start:
            raise gl.vm.UserError('the window must end after it starts')
        premium = gl.message.value
        if premium <= 0:
            raise gl.vm.UserError('send the premium with this call')
        payout = u256(premium * _PAYOUT_MULTIPLE)
        pool_after = u256(self.pool + premium)
        if pool_after - self.locked < payout:
            raise gl.vm.UserError('the pool cannot cover this payout; fund it or buy less')
        self.pool = pool_after
        self.locked = u256(self.locked + payout)
        deal = Policy(host=self.covers[name], window_start=window_start.strip(), window_end=window_end.strip(), threshold_minutes=u256(threshold), premium=premium, payout=payout, holder=gl.message.sender_address, state=STATE_OPEN, incident_id='', outcome='', minutes=u256(0), reason='')
        self.policies[key] = deal
        self.ids.append(key)
        return _as_dict(key, deal)

    @gl.public.write
    def settle(self, policy_id: str, incident_id: str) -> dict:
        key = policy_id.strip().lower()
        deal = self.policies[key]
        if deal.state != STATE_OPEN:
            raise gl.vm.UserError(f'policy is already {deal.state}: {key}')
        ref = incident_id.strip()
        if not ref or not ref.isalnum():
            raise gl.vm.UserError('incident id must be alphanumeric')
        url = 'https://' + deal.host + '/api/v2/incidents/' + ref + '.json'

        def leader_fn():
            page = ''
            try:
                resp = gl.nondet.web.get(url)
                if resp.status < 400:
                    page = (resp.body or b'').decode('utf-8', errors='replace')
            except Exception:
                page = ''
            if not page.strip():
                return {'id': '', 'created_at': '', 'resolved_at': ''}
            return _times_from_incident(page)

        def validator_fn(leaders_res) -> bool:
            if not isinstance(leaders_res, gl.vm.Return):
                return False
            leader = leaders_res.calldata
            page = ''
            try:
                resp = gl.nondet.web.get(url)
                if resp.status < 400:
                    page = (resp.body or b'').decode('utf-8', errors='replace')
            except Exception:
                page = ''
            if not page.strip():
                return str(leader['created_at']) == ''
            mine = _times_from_incident(page)
            return str(leader['id']) == mine['id'] and str(leader['created_at']) == mine['created_at'] and (str(leader['resolved_at']) == mine['resolved_at'])
        found = gl.vm.run_nondet_unsafe(leader_fn, validator_fn)
        created = str(found['created_at'])
        resolved = str(found['resolved_at'])
        returned_id = str(found['id'])
        if not created:
            raise gl.vm.UserError('that incident could not be read from ' + deal.host)
        if returned_id != ref:
            raise gl.vm.UserError('the record returned is not the incident that was requested')
        verdict = assess(created, resolved, deal.window_start, deal.window_end, int(deal.threshold_minutes))
        deal.incident_id = ref
        deal.outcome = verdict.outcome
        deal.minutes = u256(verdict.minutes)
        deal.reason = verdict.reason
        if verdict.pays:
            deal.state = STATE_PAID
            self.locked = u256(self.locked - deal.payout)
            self.pool = u256(self.pool - deal.payout)
            self.policies[key] = deal
            gl.get_contract_at(deal.holder).emit_transfer(value=deal.payout)
        else:
            self.policies[key] = deal
        return _as_dict(key, deal)

    @gl.public.write
    def close(self, policy_id: str) -> dict:
        key = policy_id.strip().lower()
        deal = self.policies[key]
        if deal.state != STATE_OPEN:
            raise gl.vm.UserError(f'policy is already {deal.state}: {key}')
        if not _window_has_passed(deal.window_end):
            raise gl.vm.UserError('the covered window has not closed yet')
        deal.state = STATE_CLOSED
        if not deal.reason:
            deal.reason = 'the window closed with no qualifying outage'
        self.locked = u256(self.locked - deal.payout)
        self.policies[key] = deal
        return _as_dict(key, deal)

    @gl.public.view
    def get_policy(self, policy_id: str) -> dict:
        key = policy_id.strip().lower()
        return _as_dict(key, self.policies[key])

    @gl.public.view
    def policy_ids(self) -> list:
        return [p for p in self.ids]

    @gl.public.view
    def count(self) -> int:
        return len(self.ids)

    @gl.public.view
    def covered(self) -> list:
        return [f'{name}:{host}' for name, host in self.covers.items()]

    @gl.public.view
    def reserves(self) -> dict:
        return {'pool': str(self.pool), 'locked': str(self.locked), 'free': str(self.pool - self.locked), 'multiple': str(_PAYOUT_MULTIPLE)}

def _window_has_passed(window_end: str) -> bool:
    stamp = str(gl.message_raw['datetime'])
    if len(stamp) < 10:
        raise gl.vm.UserError('the transaction carried no usable date')
    return parse_date(stamp[:10]) >= parse_date(window_end)

def _as_dict(key: str, deal: Policy) -> dict:
    return {'policy_id': key, 'host': deal.host, 'window_start': deal.window_start, 'window_end': deal.window_end, 'threshold_minutes': deal.threshold_minutes, 'premium': str(deal.premium), 'payout': str(deal.payout), 'holder': deal.holder.as_hex, 'state': deal.state, 'incident_id': deal.incident_id, 'outcome': deal.outcome, 'minutes': deal.minutes, 'reason': deal.reason}
