# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }
"""
Generated by deploy/build_bundle.py. Do not edit.

The deployable form of PERIL: contracts/policy.py and
contracts/peril.py pasted together, because GenVM loads one file
and cannot see sibling modules. Edit those, then rebuild.
"""

# ---- policy.py ---------------------------------------------------------

# Statuspage timestamps look like 2026-09-07T14:25:18.000Z, occasionally
# with an offset instead of Z. Only these two shapes are accepted; anything
# else is refused rather than guessed at, because a misparsed timestamp
# silently changes a payout.
_ISO_MIN = len("2026-09-07T14:25:18Z")


def _days_from_civil(y: int, m: int, d: int) -> int:
    """
    Days since 1970-01-01 for a proleptic Gregorian date.

    Hand-rolled rather than taken from `datetime`, for two reasons. The GenVM
    standard library is a subset and leaning on it invites a surprise at
    deploy time, and this is integer-only arithmetic with no locale, no
    timezone database and no floating point, so it cannot drift between one
    validator and another.

    This is Howard Hinnant's days_from_civil, which is exact across the
    whole range and handles leap years and centuries correctly.
    """
    y -= 1 if m <= 2 else 0
    era = (y if y >= 0 else y - 399) // 400
    yoe = y - era * 400
    doy = (153 * (m + (-3 if m > 2 else 9)) + 2) // 5 + d - 1
    doe = yoe * 365 + yoe // 4 - yoe // 100 + doy
    return era * 146097 + doe - 719468


def _int(text: str) -> int:
    """Strict integer parse. Empty or non-numeric raises rather than coercing."""
    if not text or not text.isdigit():
        raise ValueError("not a number: " + repr(text))
    return int(text)


def parse_iso(stamp: str) -> int:
    """
    An ISO-8601 UTC timestamp as whole seconds since the epoch.

    Fractional seconds are discarded rather than rounded. Statuspage reports
    milliseconds, and rounding could move a duration across a threshold by a
    single second, which is a payout decided by a rounding rule nobody
    agreed to. Truncating is arbitrary too, but it is arbitrary in a way
    that is written down and always favours the same side.

    Only UTC is accepted. An offset such as +02:00 is refused rather than
    converted, because a source that starts emitting offsets has changed its
    format and that deserves a failed settlement and a human look, not a
    silent reinterpretation.
    """
    s = (stamp or "").strip()
    if len(s) < _ISO_MIN or s[4] != "-" or s[7] != "-" or s[10] != "T":
        raise ValueError("not an ISO-8601 UTC timestamp: " + repr(stamp))
    if not s.endswith("Z"):
        raise ValueError("only UTC timestamps ending in Z are accepted: " + repr(stamp))
    if s[13] != ":" or s[16] != ":":
        raise ValueError("malformed time component: " + repr(stamp))

    year = _int(s[0:4])
    month = _int(s[5:7])
    day = _int(s[8:10])
    hour = _int(s[11:13])
    minute = _int(s[14:16])
    second = _int(s[17:19])

    if not (1 <= month <= 12) or not (1 <= day <= 31):
        raise ValueError("date out of range: " + repr(stamp))
    # 60 is allowed: UTC leap seconds are real and a source may emit one.
    if hour > 23 or minute > 59 or second > 60:
        raise ValueError("time out of range: " + repr(stamp))

    return _days_from_civil(year, month, day) * 86400 + hour * 3600 + minute * 60 + second


def parse_date(day: str) -> int:
    """A bare YYYY-MM-DD as seconds since the epoch, at midnight UTC."""
    s = (day or "").strip()
    if len(s) != 10 or s[4] != "-" or s[7] != "-":
        raise ValueError("not a YYYY-MM-DD date: " + repr(day))
    return _days_from_civil(_int(s[0:4]), _int(s[5:7]), _int(s[8:10])) * 86400


def outage_minutes(created_at: str, resolved_at: str) -> int:
    """
    How long the incident lasted, in whole minutes, rounded down.

    Rounding down means a 59 minute 59 second outage does not clear a sixty
    minute threshold. That is the conservative direction: it refuses a
    borderline payout rather than granting one, and a buyer can price around
    a rule that is written down.
    """
    start = parse_iso(created_at)
    end = parse_iso(resolved_at)
    if end < start:
        raise ValueError("incident resolved before it started")
    return (end - start) // 60


# The four ways a settlement can end. Strings rather than an enum so the
# value stored on chain reads the same as the value in a test.
PAYS = "pays"
UNDER_THRESHOLD = "under_threshold"
OUTSIDE_WINDOW = "outside_window"
UNRESOLVED = "unresolved"


class Assessment:
    """
    The result of measuring one incident against one policy.

    A plain class rather than a dataclass because the bundle that gets
    deployed is a single file and the fewer decorators it depends on the
    fewer ways it can fail to load.
    """

    def __init__(self, outcome: str, minutes: int, reason: str):
        self.outcome = outcome
        self.minutes = minutes
        self.reason = reason

    @property
    def pays(self) -> bool:
        return self.outcome == PAYS


def assess(
    created_at: str,
    resolved_at: str,
    window_start: str,
    window_end: str,
    threshold_minutes: int,
) -> Assessment:
    """
    Decide whether one incident triggers one policy.

    Three questions in order, cheapest first, and each one can only refuse:

      Is the incident over? An incident still in progress has no duration
      yet. Settling on a partial outage would let a claimant settle early
      during a long failure and take a smaller payout than they were owed,
      or settle repeatedly as it grew.

      Did it start inside the covered window? The window is half open,
      [start, end), so an incident beginning at the exact instant a window
      closes belongs to the next one and cannot be claimed twice.

      Was it long enough? Compared against the threshold the buyer agreed
      to when the policy was written, which is the only number in this whole
      decision that a human chose.
    """
    if not (resolved_at or "").strip():
        return Assessment(
            UNRESOLVED,
            0,
            "the incident is still open, so it has no final duration to measure",
        )

    minutes = outage_minutes(created_at, resolved_at)
    began = parse_iso(created_at)

    if began < parse_date(window_start) or began >= parse_date(window_end):
        return Assessment(
            OUTSIDE_WINDOW,
            minutes,
            "the incident began outside the covered window",
        )

    if minutes < threshold_minutes:
        return Assessment(
            UNDER_THRESHOLD,
            minutes,
            f"{minutes} minutes is under the {threshold_minutes} minute threshold",
        )

    return Assessment(
        PAYS,
        minutes,
        f"{minutes} minutes meets the {threshold_minutes} minute threshold",
    )


# ---- peril.py ----------------------------------------------------------

from dataclasses import dataclass

from genlayer import *


# What a premium buys. Fixed at deployment rather than per policy, because a
# multiple the seller could set per sale is a price, and pricing risk needs
# an underwriter making judgements, which is exactly what this design is
# built to do without.
_PAYOUT_MULTIPLE = 10

# Bounds on a threshold. Below the floor a policy would pay out on ordinary
# blips that every service has weekly; above the ceiling it would never pay
# and the premium is simply taken.
_MIN_THRESHOLD = 15
_MAX_THRESHOLD = 1440

STATE_OPEN = "open"
STATE_PAID = "paid"
STATE_CLOSED = "closed"


def _times_from_incident(body: str) -> dict:
    """
    The two timestamps a settlement depends on, and nothing else.

    Deliberately narrow. A Statuspage response carries fields that move
    between requests, including the page's own updated_at, so comparing
    whole bodies would make honest validators disagree about a record that
    had not changed.
    """
    import json

    data = json.loads(body)
    incident = data.get("incident") or {}
    return {
        "id": str(incident.get("id") or ""),
        "created_at": str(incident.get("created_at") or ""),
        "resolved_at": str(incident.get("resolved_at") or ""),
    }


@allow_storage
@dataclass
class Policy:
    host: str
    window_start: str
    window_end: str
    threshold_minutes: u256
    premium: u256
    payout: u256
    holder: Address
    state: str
    # Filled in at settlement. Empty until then, and never written twice.
    incident_id: str
    outcome: str
    minutes: u256
    reason: str


class Peril(gl.Contract):
    covers: TreeMap[str, str]
    policies: TreeMap[str, Policy]
    ids: DynArray[str]
    # Value committed to open policies. The pool can only sell cover it
    # could actually pay, so this is checked before every sale.
    locked: u256
    pool: u256

    def __init__(self):
        # The registry. Fixed here, at deployment, where everyone can read
        # it and nobody can add to it later. Every one of these was fetched
        # and confirmed to answer on /api/v2/incidents/{id}.json.
        self.covers["cloudflare"] = "www.cloudflarestatus.com"
        self.covers["github"] = "www.githubstatus.com"
        self.covers["openai"] = "status.openai.com"
        self.covers["discord"] = "discordstatus.com"
        self.covers["vercel"] = "www.vercel-status.com"
        self.covers["netlify"] = "www.netlifystatus.com"
        self.covers["npm"] = "status.npmjs.org"
        self.locked = u256(0)
        self.pool = u256(0)

    # ----------------------------------------------------------------
    # the pool
    # ----------------------------------------------------------------

    @gl.public.write.payable
    def fund(self) -> dict:
        """
        Add to the pool that pays claims.

        Open to anyone. Whoever funds it takes the risk and keeps the
        premiums of policies that never trigger, which is underwriting.
        """
        amount = gl.message.value
        if amount <= 0:
            raise gl.vm.UserError("send value with this call")
        self.pool = u256(self.pool + amount)
        return {"pool": str(self.pool), "locked": str(self.locked)}

    # ----------------------------------------------------------------
    # buying cover
    # ----------------------------------------------------------------

    @gl.public.write.payable
    def buy(
        self,
        policy_id: str,
        cover: str,
        window_start: str,
        window_end: str,
        threshold_minutes: int,
    ) -> dict:
        """
        Buy cover. The value sent is the premium; the payout is a fixed
        multiple of it, locked from the pool for as long as the policy runs.

        `cover` is a key into the registry, not an address. The contract
        resolves it to a host itself.
        """
        key = policy_id.strip().lower()
        if key in self.policies:
            raise gl.vm.UserError(f"policy already exists: {key}")

        name = cover.strip().lower()
        if name not in self.covers:
            raise gl.vm.UserError(
                "not a covered service; call covered() for the list"
            )

        threshold = int(threshold_minutes)
        if threshold < _MIN_THRESHOLD or threshold > _MAX_THRESHOLD:
            raise gl.vm.UserError(
                f"threshold must be between {_MIN_THRESHOLD} and "
                f"{_MAX_THRESHOLD} minutes"
            )

        # Parsing here rather than at settlement means a malformed window is
        # refused at the counter, when the buyer can still fix it, instead
        # of silently producing a policy that can never settle.
        start = parse_date(window_start)
        end = parse_date(window_end)
        if end <= start:
            raise gl.vm.UserError("the window must end after it starts")

        premium = gl.message.value
        if premium <= 0:
            raise gl.vm.UserError("send the premium with this call")

        payout = u256(premium * _PAYOUT_MULTIPLE)

        # The premium joins the pool before solvency is checked, because it
        # is part of what backs this policy. What must hold afterwards is
        # that every open policy could still be paid in full.
        pool_after = u256(self.pool + premium)
        if pool_after - self.locked < payout:
            raise gl.vm.UserError(
                "the pool cannot cover this payout; fund it or buy less"
            )

        self.pool = pool_after
        self.locked = u256(self.locked + payout)

        deal = Policy(
            host=self.covers[name],
            window_start=window_start.strip(),
            window_end=window_end.strip(),
            threshold_minutes=u256(threshold),
            premium=premium,
            payout=payout,
            holder=gl.message.sender_address,
            state=STATE_OPEN,
            incident_id="",
            outcome="",
            minutes=u256(0),
            reason="",
        )
        self.policies[key] = deal
        self.ids.append(key)
        return _as_dict(key, deal)

    # ----------------------------------------------------------------
    # settling
    # ----------------------------------------------------------------

    @gl.public.write
    def settle(self, policy_id: str, incident_id: str) -> dict:
        """
        Measure one published incident against one policy.

        Callable by anyone. The outcome is fixed by the incident record and
        the numbers the buyer already agreed to, so there is nothing a
        caller could bias by being the one to ask. A privileged settler
        would reintroduce the very thing this removes: somebody who decides
        whether you get paid.
        """
        key = policy_id.strip().lower()
        deal = self.policies[key]
        if deal.state != STATE_OPEN:
            raise gl.vm.UserError(f"policy is already {deal.state}: {key}")

        ref = incident_id.strip()
        if not ref or not ref.isalnum():
            raise gl.vm.UserError("incident id must be alphanumeric")

        # Built from the registry host, never from anything the caller sent.
        url = "https://" + deal.host + "/api/v2/incidents/" + ref + ".json"

        def leader_fn():
            page = ""
            try:
                resp = gl.nondet.web.get(url)
                if resp.status < 400:
                    page = (resp.body or b"").decode("utf-8", errors="replace")
            except Exception:
                page = ""
            if not page.strip():
                return {"id": "", "created_at": "", "resolved_at": ""}
            return _times_from_incident(page)

        def validator_fn(leaders_res) -> bool:
            if not isinstance(leaders_res, gl.vm.Return):
                return False
            leader = leaders_res.calldata

            page = ""
            try:
                resp = gl.nondet.web.get(url)
                if resp.status < 400:
                    page = (resp.body or b"").decode("utf-8", errors="replace")
            except Exception:
                page = ""

            if not page.strip():
                # Unreadable for me too, so the only claim I can honestly
                # agree with is that nothing was read.
                return str(leader["created_at"]) == ""

            mine = _times_from_incident(page)
            return (
                str(leader["id"]) == mine["id"]
                and str(leader["created_at"]) == mine["created_at"]
                and str(leader["resolved_at"]) == mine["resolved_at"]
            )

        found = gl.vm.run_nondet_unsafe(leader_fn, validator_fn)

        created = str(found["created_at"])
        resolved = str(found["resolved_at"])
        returned_id = str(found["id"])

        if not created:
            raise gl.vm.UserError(
                "that incident could not be read from " + deal.host
            )
        # The record has to be the one that was asked for. Without this a
        # host that answers every path with its newest incident would settle
        # policies against something nobody named.
        if returned_id != ref:
            raise gl.vm.UserError(
                "the record returned is not the incident that was requested"
            )

        # Deterministic from here. Every node holds the same two timestamps,
        # so each reaches the same verdict as ordinary contract code without
        # another round of consensus.
        verdict = assess(
            created,
            resolved,
            deal.window_start,
            deal.window_end,
            int(deal.threshold_minutes),
        )

        deal.incident_id = ref
        deal.outcome = verdict.outcome
        deal.minutes = u256(verdict.minutes)
        deal.reason = verdict.reason

        if verdict.pays:
            deal.state = STATE_PAID
            self.locked = u256(self.locked - deal.payout)
            self.pool = u256(self.pool - deal.payout)
            self.policies[key] = deal
            # State is settled before any value moves, and the transfer is
            # emitted on finalisation so a transaction that later rolls back
            # cannot have moved real funds.
            gl.get_contract_at(deal.holder).emit_transfer(value=deal.payout)
        else:
            # A policy that does not pay stays open. One incident failing to
            # clear the bar says nothing about the next one, and closing it
            # here would let anyone burn a policy by settling it against a
            # two minute blip on its first day.
            self.policies[key] = deal

        return _as_dict(key, deal)

    @gl.public.write
    def close(self, policy_id: str) -> dict:
        """
        Release the cover behind a policy whose window has passed.

        Anyone may call it, because it only ever returns money to the pool
        and the window either has closed or has not. Without it the cover
        for every expired policy would stay locked forever and the pool
        would slowly stop being able to sell anything.
        """
        key = policy_id.strip().lower()
        deal = self.policies[key]
        if deal.state != STATE_OPEN:
            raise gl.vm.UserError(f"policy is already {deal.state}: {key}")

        # An incident that began before the window closed can still be
        # settled after it, so closing waits until nothing new can qualify.
        if not _window_has_passed(deal.window_end):
            raise gl.vm.UserError("the covered window has not closed yet")

        deal.state = STATE_CLOSED
        if not deal.reason:
            deal.reason = "the window closed with no qualifying outage"
        self.locked = u256(self.locked - deal.payout)
        self.policies[key] = deal
        return _as_dict(key, deal)

    # ----------------------------------------------------------------
    # reading
    # ----------------------------------------------------------------

    @gl.public.view
    def get_policy(self, policy_id: str) -> dict:
        key = policy_id.strip().lower()
        return _as_dict(key, self.policies[key])

    @gl.public.view
    def policy_ids(self) -> list:
        return [p for p in self.ids]

    @gl.public.view
    def count(self) -> int:
        return len(self.ids)

    @gl.public.view
    def covered(self) -> list:
        return [f"{name}:{host}" for name, host in self.covers.items()]

    @gl.public.view
    def reserves(self) -> dict:
        """What the pool holds, what it owes, and what it could still sell."""
        return {
            "pool": str(self.pool),
            "locked": str(self.locked),
            "free": str(self.pool - self.locked),
            "multiple": str(_PAYOUT_MULTIPLE),
        }


def _window_has_passed(window_end: str) -> bool:
    """
    Has the covered window closed?

    Read from the transaction rather than from a wall clock. `gl.message`
    carries no time, but `gl.message_raw` has a `datetime` string that is
    part of the message itself, so every validator in a round sees the same
    value. A machine clock would differ between them and the round would
    never agree.

    Only the date part is used. The exact time format of that field is not
    documented and a stricter parse would break the moment it changed
    shape, while a window always ends at midnight anyway, so a day is all
    the precision this decision needs.
    """
    stamp = str(gl.message_raw["datetime"])
    if len(stamp) < 10:
        raise gl.vm.UserError("the transaction carried no usable date")
    return parse_date(stamp[:10]) >= parse_date(window_end)


def _as_dict(key: str, deal: Policy) -> dict:
    return {
        "policy_id": key,
        "host": deal.host,
        "window_start": deal.window_start,
        "window_end": deal.window_end,
        "threshold_minutes": deal.threshold_minutes,
        "premium": str(deal.premium),
        "payout": str(deal.payout),
        "holder": deal.holder.as_hex,
        "state": deal.state,
        "incident_id": deal.incident_id,
        "outcome": deal.outcome,
        "minutes": deal.minutes,
        "reason": deal.reason,
    }
